"""empty message

Revision ID: 11ba934329c6
Revises: 
Create Date: 2020-08-15 15:36:11.328303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11ba934329c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='用户ID'),
    sa.Column('username', sa.String(length=30), nullable=False, comment='用户名'),
    sa.Column('password', sa.String(length=30), nullable=False, comment='密码'),
    sa.Column('phone', sa.String(length=11), nullable=False, comment='手机号码'),
    sa.Column('email', sa.String(length=30), nullable=True, comment='邮箱'),
    sa.Column('icon', sa.String(length=300), nullable=True, comment='用户头像'),
    sa.Column('isdelete', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('rdatetime', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('article',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='文章ID'),
    sa.Column('title', sa.String(length=50), nullable=False, comment='文章标题'),
    sa.Column('content', sa.String(length=300), nullable=False, comment='文章内容'),
    sa.Column('pdatetime', sa.DateTime(), nullable=True, comment='发布时间'),
    sa.Column('click_num', sa.Integer(), nullable=True, comment='浏览数'),
    sa.Column('save_num', sa.Integer(), nullable=True, comment='收藏数'),
    sa.Column('love_num', sa.Integer(), nullable=True, comment='点赞数'),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article')
    op.drop_table('user')
    # ### end Alembic commands ###
